In [5]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [9]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5,'rokon'))

print(arr)

['1' '2' '3' '4' '5' 'rokon']


In [7]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [31]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print('2nd element on 1st row: ', arr[1, 1])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  7


In [27]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('5th element on 2nd row: ', arr[0, 3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  4


In [32]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [15]:
import numpy as np
one_d_array = np.arange(27)
print(one_d_array)
one_d_array.shape=(3,3,3)
tow_d_arrd = one_d_array
print(tow_d_arrd)






[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
import numpy as np

# Creating a 1D array with 27 elements
one_d_array = np.arange(13)
print("1D array:")
print(one_d_array)

# Reshaping the array into a 3D array with shape (3, 3, 3)
one_d_array.shape = (3, 3, 3)
three_d_array = one_d_array
print("\n3D array:")
print(three_d_array)

# Accessing an element in the 3D array
print('\nElement at 2nd layer, 1st row, 2nd column: ', three_d_array[1, 1, 1])


1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


ValueError: cannot reshape array of size 13 into shape (3,3,3)

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [3]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32
